apiVersion: v1
kind: Service
metadata:
  name: capstone-frontend-service
spec:
  type: NodePort
  selector:
    app: capstone-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30090

